### ISSUE TITLE
Remove "Read More" in Blog section of Home Page

### ISSUE THREAD

**Issue by tashi2408** [tashi2408/yourFriend#1]
* Read More button which displays on hover is not consistent with the purple buttons.
* Remove the "Read more" cause there will be only **4 blogs**.

![image](https://user-images.githubusercontent.com/63187583/156192172-02718f80-82e4-4dff-83be-8112c8b16ee3.png)

**Comment by jaas666** [comment]
## Submitted PR #7 
1. I couldn't find the **Read More** at the bottom of the blog page. Maybe it was already removed?
2. I removed the border radius from the `.blogContent .btn` selector in order to make buttons consistent wit the others.
