### ISSUE TITLE
Fixing color, theme and design on Login/Register  

### ISSUE THREAD

**Issue by tashi2408** [tashi2408/yourFriend#5]
1. Set background color as purple. Use purple defined as css variable.
2. Change the Signup now on Login to purple button. Similarly on the Register page.
3. Change the blue color in google button to purple or  a shade of white whichever suits.

![image](https://user-images.githubusercontent.com/63187583/156196563-1fa8b02e-3b72-4608-9ada-b3aedb06d542.png)

**Comment by jaas666** [comment]
# Submitted PR for this issue.

As for the 3rd request:

> Change the blue color in google button to purple or a shade of white whichever suits.

 [Google guidelines](https://developers.google.com/identity/branding-guidelines) do not allow the change the color on the sign-in button.
